name: Manual Inputs
on:
  workflow_dispatch:
    inputs:
      version:
        description: Load json
        default: conf.json
        required: true
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 
      print_tags:
        description: 'True to print to STDOUT'
        required: true 
        type: boolean 
      print_tags.one:
        description: 'Look at me'
        required: true
        type: boolean
      tags:
        description: 'Test scenario tags'
        required: true 
        type: string
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true 
jobs:
  push-data:
    name: Push json data
    runs-on: ubuntu-latest
    #steps:
    #  - name: Example variable usage
    #    run: git tag ${{ github.event.inputs.version }}
    steps:
      #- id: set_var
        #run:
          #data = `ls`
          #echo data
          #content=`cat conf.json`
          # the following lines are only required for multi line json
          #content="${content//'%'/'%25'}"
          #content="${content//$'\n'/'%0A'}"
          #content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          #echo "::set-output name=packageJson::$content"
      #- run: |
      #    echo "${{fromJson(steps.set_var.outputs.packageJson).version}}"
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"

      - uses: actions/checkout@v1

      - name: Fetch action
        id: pl
        uses: Rishabh510/Path-lister-action@master
        with:
          path: ".github/"
          type: ".yml"

      - name: Output results
        run: |
          echo "Found ${{ steps.pl.outputs.path_count }} file(s) with this extension:"
          for i in ${{ steps.pl.outputs.paths }}; do
          echo $i
          done
